//! AI agent workflow — domain types for task planning, step execution,
//! observation, and iterative refinement.
//!
//! Phase 4: agent orchestrator with plan→execute→observe→iterate loop.
//! The agent can decompose user goals into step-by-step plans, execute actions
//! via tools and AI calls, observe results, and adapt when needed.

use serde::{Deserialize, Serialize};

use crate::actions::ActionKind;

/// The high-level state of an agent session.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum AgentState {
    /// No active session.
    Idle,
    /// The agent is decomposing the goal into a plan.
    Planning,
    /// Waiting for user approval of the generated plan.
    AwaitingPlanApproval,
    /// Executing planned steps.
    Executing,
    /// Waiting for user approval before applying a proposed edit.
    AwaitingEditApproval,
    /// Observation phase — reading results of an executed step.
    Observing,
    /// All steps complete successfully.
    Completed,
    /// An unrecoverable error occurred.
    Failed,
    /// User cancelled the session.
    Cancelled,
}

impl AgentState {
    pub fn is_terminal(&self) -> bool {
        matches!(self, AgentState::Completed | AgentState::Failed | AgentState::Cancelled)
    }

    pub fn is_active(&self) -> bool {
        !self.is_terminal() && *self != AgentState::Idle
    }

    pub fn display_name(&self) -> &'static str {
        match self {
            AgentState::Idle => "Idle",
            AgentState::Planning => "Planning",
            AgentState::AwaitingPlanApproval => "Awaiting Approval",
            AgentState::Executing => "Executing",
            AgentState::AwaitingEditApproval => "Reviewing Edit",
            AgentState::Observing => "Observing",
            AgentState::Completed => "Complete",
            AgentState::Failed => "Failed",
            AgentState::Cancelled => "Cancelled",
        }
    }
}

/// A single step in a task plan.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct TaskStep {
    /// Sequence number (1-based).
    pub step_number: usize,
    /// What action to perform.
    pub action: ActionKind,
    /// Human-readable description of what this step does.
    pub description: String,
    /// The tool or AI capability to use.
    pub tool: String,
    /// Expected target (file, buffer, etc.).
    pub target: Option<String>,
    /// Expected outcome description.
    pub expected_outcome: String,
    /// Execution result after the step runs.
    pub result: Option<StepResult>,
    /// Whether this step has been executed.
    pub executed: bool,
}

/// Result of executing a single task step.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct StepResult {
    pub success: bool,
    pub output: String,
    pub summary: String,
    pub diff_summary: Option<String>,
}

/// A complete task plan generated by the AI.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct TaskPlan {
    /// Unique plan identifier.
    pub plan_id: String,
    /// The user's original goal/request.
    pub goal: String,
    /// High-level reasoning about the approach.
    pub reasoning: String,
    /// Ordered sequence of steps.
    pub steps: Vec<TaskStep>,
    /// Whether the user has approved this plan.
    pub approved: bool,
    /// Estimated complexity (1-5).
    pub complexity_estimate: u8,
    /// Estimated total steps (before decomposition).
    pub estimated_total_steps: usize,
}

impl TaskPlan {
    pub fn new(goal: impl Into<String>, reasoning: impl Into<String>) -> Self {
        Self {
            plan_id: uuid::Uuid::new_v4().to_string(),
            goal: goal.into(),
            reasoning: reasoning.into(),
            steps: Vec::new(),
            approved: false,
            complexity_estimate: 1,
            estimated_total_steps: 0,
        }
    }

    pub fn add_step(&mut self, step: TaskStep) {
        self.steps.push(step);
        self.estimated_total_steps = self.steps.len();
    }

    pub fn current_step(&self) -> Option<&TaskStep> {
        self.steps.iter().find(|s| !s.executed)
    }

    pub fn current_step_index(&self) -> usize {
        self.steps.iter().position(|s| !s.executed).unwrap_or(self.steps.len())
    }

    pub fn progress_frac(&self) -> f32 {
        if self.steps.is_empty() {
            0.0
        } else {
            let done = self.steps.iter().filter(|s| s.executed).count() as f32;
            done / self.steps.len() as f32
        }
    }

    pub fn is_complete(&self) -> bool {
        self.steps.iter().all(|s| s.executed)
    }
}

/// Full agent session state.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct AgentSession {
    /// Session identifier.
    pub session_id: String,
    /// Current state.
    pub state: AgentState,
    /// The generated plan (if any).
    pub plan: Option<TaskPlan>,
    /// History of observations / tool results during execution.
    pub execution_log: Vec<String>,
    /// Error message if state is Failed.
    pub error_message: Option<String>,
    /// User feedback on the plan or edits.
    pub user_feedback: Option<String>,
    /// Whether the user has been prompted for the current wait.
    pub user_prompted: bool,
}

impl Default for AgentSession {
    fn default() -> Self {
        Self::new()
    }
}

impl AgentSession {
    pub fn new() -> Self {
        Self {
            session_id: uuid::Uuid::new_v4().to_string(),
            state: AgentState::Idle,
            plan: None,
            execution_log: Vec::new(),
            error_message: None,
            user_feedback: None,
            user_prompted: false,
        }
    }

    pub fn start_planning(&mut self, goal: &str) {
        self.state = AgentState::Planning;
        self.plan = Some(TaskPlan::new(goal, "Generating plan..."));
        self.execution_log.clear();
        self.error_message = None;
        self.user_feedback = None;
        self.user_prompted = false;
    }

    pub fn plan_ready(&mut self) {
        self.state = AgentState::AwaitingPlanApproval;
        self.user_prompted = true;
    }

    pub fn approve_plan(&mut self) {
        if let Some(ref mut plan) = self.plan {
            plan.approved = true;
        }
        self.state = AgentState::Executing;
        self.user_prompted = false;
    }

    pub fn reject_plan(&mut self, reason: &str) {
        self.user_feedback = Some(reason.to_string());
        self.state = AgentState::Planning;
        self.user_prompted = false;
    }

    pub fn step_executed(&mut self, result: StepResult) {
        let summary = result.summary.clone();
        if let Some(ref mut plan) = self.plan {
            for step in &mut plan.steps {
                if !step.executed {
                    step.executed = true;
                    step.result = Some(result);
                    break;
                }
            }
            let idx = plan.current_step_index().saturating_sub(1).max(1);
            self.execution_log.push(format!("Step {idx}: {summary}"));
        }
    }

    pub fn request_edit_approval(&mut self) {
        self.state = AgentState::AwaitingEditApproval;
        self.user_prompted = true;
    }

    pub fn edit_approved(&mut self) {
        self.state = AgentState::Executing;
        self.user_prompted = false;
    }

    pub fn edit_rejected(&mut self, reason: &str) {
        self.user_feedback = Some(reason.to_string());
        self.state = AgentState::Executing;
        self.user_prompted = false;
    }

    pub fn start_observing(&mut self) {
        self.state = AgentState::Observing;
    }

    pub fn complete(&mut self, summary: &str) {
        self.state = AgentState::Completed;
        self.execution_log.push(format!("Completed: {summary}"));
    }

    pub fn fail(&mut self, error: &str) {
        self.state = AgentState::Failed;
        self.error_message = Some(error.to_string());
    }

    pub fn cancel(&mut self) {
        self.state = AgentState::Cancelled;
    }

    pub fn reset(&mut self) {
        *self = Self::new();
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn agent_state_transitions() {
        let mut session = AgentSession::new();
        assert_eq!(session.state, AgentState::Idle);

        session.start_planning("fix bugs");
        assert_eq!(session.state, AgentState::Planning);

        session.plan_ready();
        assert_eq!(session.state, AgentState::AwaitingPlanApproval);

        session.approve_plan();
        assert_eq!(session.state, AgentState::Executing);

        session.complete("done");
        assert_eq!(session.state, AgentState::Completed);
    }

    #[test]
    fn plan_tracks_progress() {
        let mut plan = TaskPlan::new("test goal", "reasoning");
        plan.add_step(TaskStep {
            step_number: 1,
            action: ActionKind::Explain,
            description: "explain code".into(),
            tool: "ai".into(),
            target: Some("main.rs".into()),
            expected_outcome: "understanding".into(),
            result: None,
            executed: false,
        });
        plan.add_step(TaskStep {
            step_number: 2,
            action: ActionKind::Edit,
            description: "fix".into(),
            tool: "ai".into(),
            target: None,
            expected_outcome: "fixed".into(),
            result: None,
            executed: false,
        });

        assert!(!plan.is_complete());
        assert_eq!(plan.progress_frac(), 0.0);
        assert_eq!(plan.current_step_index(), 0);
    }

    #[test]
    fn session_cancel_resets() {
        let mut session = AgentSession::new();
        session.start_planning("test");
        session.cancel();
        assert_eq!(session.state, AgentState::Cancelled);
        session.reset();
        assert_eq!(session.state, AgentState::Idle);
    }

    #[test]
    fn step_execution_updates_plan() {
        let mut session = AgentSession::new();
        session.start_planning("test");
        let mut plan = TaskPlan::new("goal", "reasoning");
        plan.add_step(TaskStep {
            step_number: 1,
            action: ActionKind::Edit,
            description: "edit".into(),
            tool: "ai".into(),
            target: None,
            expected_outcome: "done".into(),
            result: None,
            executed: false,
        });
        session.plan = Some(plan);

        session.step_executed(StepResult {
            success: true,
            output: "changed 5 lines".into(),
            summary: "edited file".into(),
            diff_summary: Some("5 lines changed".into()),
        });

        let plan = session.plan.as_ref().unwrap();
        assert!(plan.steps[0].executed);
        assert!(plan.steps[0].result.is_some());
    }
}
