//! Edit-flow state machine — models the full lifecycle of AI-proposed edits
//! from proposal through review, approval, application, and verification.
//!
//! Phase 4: structured edit review workflow with user approval gates.
//! Integrates with the diff engine and text transaction pipeline.

use serde::{Deserialize, Serialize};

use crate::actions::DiffResult;

/// The lifecycle stage of an edit flow.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum EditFlowStage {
    /// No edit in progress.
    Idle,
    /// AI is generating the edit proposal.
    Generating,
    /// Proposal is ready for user review.
    Reviewing,
    /// User accepted — applying changes.
    Applying,
    /// Changes applied — verifying result.
    Verifying,
    /// Edit applied successfully.
    Applied,
    /// User rejected the proposal.
    Rejected,
    /// Edit failed during apply or verify.
    Failed,
}

impl EditFlowStage {
    pub fn display_name(&self) -> &'static str {
        match self {
            EditFlowStage::Idle => "Idle",
            EditFlowStage::Generating => "Generating",
            EditFlowStage::Reviewing => "Review",
            EditFlowStage::Applying => "Applying",
            EditFlowStage::Verifying => "Verifying",
            EditFlowStage::Applied => "Applied",
            EditFlowStage::Rejected => "Rejected",
            EditFlowStage::Failed => "Failed",
        }
    }

    pub fn needs_user_input(&self) -> bool {
        *self == EditFlowStage::Reviewing
    }

    pub fn is_terminal(&self) -> bool {
        matches!(self, EditFlowStage::Applied | EditFlowStage::Rejected | EditFlowStage::Failed)
    }

    pub fn is_active(&self) -> bool {
        !matches!(self, EditFlowStage::Idle) && !self.is_terminal()
    }
}

/// An edit proposal generated by the AI.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct EditProposal {
    /// Unique proposal id.
    pub proposal_id: String,
    /// The target buffer/file.
    pub target_buffer: String,
    /// Human-readable summary of the proposed change.
    pub summary: String,
    /// The structured diff changes.
    pub diff: DiffResult,
    /// Full AI response text (for display).
    pub ai_response: String,
    /// Whether the proposal has been reviewed.
    pub reviewed: bool,
    /// User decision: accepted/rejected.
    pub decision: Option<EditDecision>,
    /// User's optional feedback.
    pub feedback: Option<String>,
}

impl EditProposal {
    pub fn new(
        target_buffer: impl Into<String>,
        summary: impl Into<String>,
        diff: DiffResult,
        ai_response: impl Into<String>,
    ) -> Self {
        Self {
            proposal_id: uuid::Uuid::new_v4().to_string(),
            target_buffer: target_buffer.into(),
            summary: summary.into(),
            diff,
            ai_response: ai_response.into(),
            reviewed: false,
            decision: None,
            feedback: None,
        }
    }
}

/// User's decision on an edit proposal.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum EditDecision {
    Accepted,
    Rejected,
    Modified,
}

/// The result of applying an edit.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct EditApplyResult {
    pub proposal_id: String,
    pub success: bool,
    pub message: String,
    pub lines_changed: Option<usize>,
}

/// The full edit flow state machine.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct EditFlow {
    pub stage: EditFlowStage,
    pub proposal: Option<EditProposal>,
    pub apply_result: Option<EditApplyResult>,
    pub error_message: Option<String>,
    /// Whether the last apply previewed correctly.
    pub preview_ok: bool,
}

impl Default for EditFlow {
    fn default() -> Self {
        Self::new()
    }
}

impl EditFlow {
    pub fn new() -> Self {
        Self {
            stage: EditFlowStage::Idle,
            proposal: None,
            apply_result: None,
            error_message: None,
            preview_ok: false,
        }
    }

    pub fn start_generation(&mut self) {
        self.stage = EditFlowStage::Generating;
        self.proposal = None;
        self.apply_result = None;
        self.error_message = None;
    }

    pub fn proposal_ready(&mut self, proposal: EditProposal) {
        self.proposal = Some(proposal);
        self.stage = EditFlowStage::Reviewing;
    }

    pub fn accept(&mut self) -> Result<(), String> {
        if self.stage != EditFlowStage::Reviewing {
            return Err(format!("cannot accept in stage {:?}", self.stage));
        }
        if let Some(ref mut p) = self.proposal {
            p.reviewed = true;
            p.decision = Some(EditDecision::Accepted);
        }
        self.stage = EditFlowStage::Applying;
        Ok(())
    }

    pub fn reject(&mut self, reason: &str) -> Result<(), String> {
        if self.stage != EditFlowStage::Reviewing {
            return Err(format!("cannot reject in stage {:?}", self.stage));
        }
        if let Some(ref mut p) = self.proposal {
            p.reviewed = true;
            p.decision = Some(EditDecision::Rejected);
            p.feedback = Some(reason.to_string());
        }
        self.stage = EditFlowStage::Rejected;
        Ok(())
    }

    pub fn modify(&mut self) -> Result<(), String> {
        if self.stage != EditFlowStage::Reviewing {
            return Err(format!("cannot modify in stage {:?}", self.stage));
        }
        if let Some(ref mut p) = self.proposal {
            p.decision = Some(EditDecision::Modified);
        }
        self.stage = EditFlowStage::Generating;
        Ok(())
    }

    pub fn apply_complete(&mut self, result: EditApplyResult) {
        self.apply_result = Some(result.clone());
        if result.success {
            self.stage = EditFlowStage::Applied;
        } else {
            self.stage = EditFlowStage::Failed;
            self.error_message = Some(result.message.clone());
        }
    }

    pub fn fail(&mut self, error: &str) {
        self.stage = EditFlowStage::Failed;
        self.error_message = Some(error.to_string());
    }

    pub fn reset(&mut self) {
        *self = Self::new();
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::actions::DiffResult;

    fn sample_proposal() -> EditProposal {
        EditProposal::new(
            "buf:main",
            "add import",
            DiffResult::empty("buf:main"),
            "added use std::io;",
        )
    }

    #[test]
    fn edit_flow_lifecycle() {
        let mut flow = EditFlow::new();
        assert_eq!(flow.stage, EditFlowStage::Idle);

        flow.start_generation();
        assert_eq!(flow.stage, EditFlowStage::Generating);

        flow.proposal_ready(sample_proposal());
        assert_eq!(flow.stage, EditFlowStage::Reviewing);
        assert!(flow.stage.needs_user_input());

        flow.accept().unwrap();
        assert_eq!(flow.stage, EditFlowStage::Applying);

        flow.apply_complete(EditApplyResult {
            proposal_id: "test".into(),
            success: true,
            message: "ok".into(),
            lines_changed: Some(3),
        });
        assert_eq!(flow.stage, EditFlowStage::Applied);
    }

    #[test]
    fn edit_flow_rejection() {
        let mut flow = EditFlow::new();
        flow.start_generation();
        flow.proposal_ready(sample_proposal());
        flow.reject("not what I wanted").unwrap();
        assert_eq!(flow.stage, EditFlowStage::Rejected);
        assert!(flow.stage.is_terminal());
    }

    #[test]
    fn edit_flow_apply_failure() {
        let mut flow = EditFlow::new();
        flow.start_generation();
        flow.proposal_ready(sample_proposal());
        flow.accept().unwrap();
        flow.apply_complete(EditApplyResult {
            proposal_id: "test".into(),
            success: false,
            message: "buffer not found".into(),
            lines_changed: None,
        });
        assert_eq!(flow.stage, EditFlowStage::Failed);
    }

    #[test]
    fn accept_out_of_stage_errors() {
        let mut flow = EditFlow::new();
        assert!(flow.accept().is_err());
    }

    #[test]
    fn reject_out_of_stage_errors() {
        let mut flow = EditFlow::new();
        assert!(flow.reject("nope").is_err());
    }
}
