//! Shared headless [`GuiApp`] builder for in-crate behaviour tests.
//!
//! Constructing a `GuiApp` requires every field to be provided explicitly
//! (there is no window/GPU in a unit test).  Keeping a single authoritative
//! builder here avoids drift between test modules and mirrors the external
//! harness in `tests/widget_activation_dispatch.rs`.
#![cfg(test)]

use super::GuiApp;
use crate::gui::window::editor_buf::EditorBufferState;
use crate::gui::{ShellFrame, ShellWorkContent, Size};
use zaroxi_core_engine_style::test_utils::test_tokens_dark;
use zaroxi_core_engine_ui::{ShellLayout, WidgetInteractionModel, build_shell_widget_tree};
use zaroxi_interface_theme::theme::ZaroxiTheme;

/// Build a fully-initialised headless `GuiApp` with no window, no workspace
/// service, and an empty editor.  Individual tests override the specific
/// fields they exercise (e.g. `composition`, `workspace_service`,
/// `editor_group`).
pub(crate) fn make_headless_app() -> GuiApp {
    let tokens = test_tokens_dark();
    let layout = ShellLayout::from_window_size(1200, 800);
    let (ai_tracer, ai_trace_rx) = zaroxi_application_ai::trace::AiTracer::channel();
    GuiApp {
        window_attributes: Default::default(),
        title: "test".into(),
        maybe_window: None,
        shell: ShellFrame::new(Size { width: 1200, height: 800 }, ZaroxiTheme::Dark),
        work_content: Some(ShellWorkContent::default()),
        requested_initial_frame: false,
        already_logged_existing: true,
        first_render_shown: true,
        widget_tree: Some(build_shell_widget_tree(&layout, &tokens, None)),
        interaction: WidgetInteractionModel::new(),
        editor_buffer: EditorBufferState::empty(),
        theme_mode: ZaroxiTheme::Dark,
        shift_held: false,
        ctrl_held: false,
        cmd_held: false,
        alt_held: false,
        terminal: Default::default(),
        bottom_tab: Default::default(),
        bottom_scroll: 0,
        problems: Vec::new(),
        parse_problems: Vec::new(),
        parse_problems_owner: None,
        output_log: Default::default(),
        mem_monitor: zaroxi_core_telemetry::MemoryMonitor::from_env(),
        buffer_tracker: zaroxi_core_telemetry::BufferActivityTracker::new(),
        last_mem_sample: None,
        ai_tracer,
        ai_trace_rx: Some(ai_trace_rx),
        ai_session: zaroxi_application_ai::view_model::AiSessionState::default(),
        on_widget_activated: None,
        composition: None,
        workspace_view: None,
        workspace_service: None,
        session_id: None,
        workspace_id: None,
        folder_picker: None,
        explorer_actions: None,
        explorer_button_rect: None,
        parser_pool: std::sync::Arc::new(zaroxi_core_platform_syntax::parser::ParserPool::new()),
        cached_editor_data: None,
        cached_editor_lines_hash: 0,
        cached_editor_spans_version: 0,
        layout_controller: crate::gui::window::editor_shell::ShellLayoutController::new(),
        editor_viewport: None,
        editor_visual_to_logical: Vec::new(),
        editor_chars_per_row: 0,
        editor_wrap_visual_offset: 0,
        needs_render: true,
        last_explorer_ids: Vec::new(),
        explorer_scroll_top: 0,
        explorer_search_active: false,
        explorer_search_rect: None,
        explorer_search_sel: None,
        rail_selected_index: 0,
        rail_hovered_index: None,
        rail_item_hit_rects: Vec::new(),
        tab_state: crate::gui::window::destination::WorkbenchTabState::new(),
        sidebar_row_hit_rects: Vec::new(),
        tab_hit_rects: Vec::new(),
        tab_arrow_left_rect: None,
        tab_arrow_right_rect: None,
        explorer_caret_blink_epoch: std::time::Instant::now(),
        explorer_visible_rows: 1,
        last_render_size: (0, 0),
        pending_scroll_frac: 0.0,
        picker_in_flight: false,
        pending_picker_rx: None,
        last_widget_tree_size: (0, 0),
        last_widget_tree_fingerprint: None,
        render_core: None,
        cockpit_text_active: false,
        cockpit_rendered_once: false,
        last_open_started_at: None,
        last_focus_change_at: None,
        status_model_generation: 0,
        startup_first_paint_done: false,
        startup_first_paint_at: None,
        startup_second_layout_reason: None,
        cockpit_retained_bytes: 0,
        editor_retained_bytes: 0,
        cockpit_status_fingerprint: 0,
        line_syntax_cache: std::collections::HashMap::new(),
        cached_line_hashes: Vec::new(),
        large_file_mode: false,
        current_language: zaroxi_core_platform_syntax::language::LanguageId::PlainText,
        latest_spans: None,
        latest_spans_version: 0,
        latest_spans_owner: None,
        last_good_highlight: None,
        cockpit_minimap: zaroxi_interface_widgets::MinimapProjection::empty(),
        cockpit_minimap_key: (None, 0, 0),
        minimap_hit_rect: None,
        minimap_dragging: false,
        git_diff_provider: zaroxi_core_platform_git::GitDiffProvider::new(),
        cockpit_diff_hunks: Vec::new(),
        cockpit_diff_version: 0,
        parse_worker: None,
        frame_scheduler: super::FrameScheduler::new(),
        ui_node_tracker: Default::default(),
        open_settling: false,
        open_burst_frames: 0,
        resize_pending: false,
        commit_deferred_open: false,
        commit_deferred_resize: false,
        open_token: 0,
        committed_open_token: 0,
        open_first_screenful_pending: false,
        pending_open: None,
        committed_active_file: None,
        file_switch_count: 0,
        visible_loading_state: false,
        open_request_at: None,
        last_upstream_open_prep_ms: 0.0,
        cached_editor_active_file: None,
        content_generation: 0,
        active_rope_owner_path: None,
        owner_reload_attempted_for: None,
        pending_owner_rehydrate: false,
        read_worker: None,
        read_token: 0,
        read_pending: false,
        read_started_at: None,
        read_generation: std::sync::Arc::new(std::sync::atomic::AtomicU64::new(0)),
        open_worker: None,
        background_open_pending: false,
        open_worker_started_at: None,
        open_present: None,
        open_atomic_first_paint: false,
        startup_geometry_initial: None,
        startup_geometry_final: None,
        startup_geometry_changed_reason: None,
        startup_first_visible_layout_stable: false,
        startup_settle_trimmed: false,
        text_instance_buffer_version: 0,
        settings: zaroxi_domain_settings::Settings::default(),
        settings_hit_rects: Vec::new(),
        settings_dropdown: zaroxi_interface_widgets::SettingsDropdownState::default(),
        cached_settings_popup: None,
        doc_buffers: std::collections::HashMap::new(),
        open_documents: std::collections::HashMap::new(),
        document_view_states: std::collections::HashMap::new(),
        restored_view_state_this_activation: false,
        activation_seq: 0,
        last_committed_activation_seq: 0,
        open_intent: None,
        editor_group: crate::gui::window::EditorGroup::default(),
        last_explorer_click: None,
    }
}
